services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: true #just a quick fix--use dependencyInjection
  StarterkitBundle\Tools\Install:
    arguments:
      $bundle: "@=service('kernel').getBundle('StarterkitBundle')"
    calls:
      - [ setTokenStorageUserResolver, [ '@Pimcore\Security\User\TokenStorageUserResolver' ] ]

  StarterkitBundle\Event\ValidKeyFormatter:
    class: StarterkitBundle\Event\ValidKeyFormatter
    tags:
      - { name: kernel.event_listener, event: pimcore.system.service.preGetValidKey, method: onGetValidKey }
      - { name: kernel.event_listener, event: pimcore.system.service.preGetValidKey, method: onGetValidPath }

  StarterkitBundle\EventListener\EditmodeListener:
    class: StarterkitBundle\EventListener\EditmodeListener
    tags:
      - { name: kernel.event_listener, event: pimcore.bundle_manager.paths.js, method: onEditObjectsJsPaths }

